### ISSUE TITLE
Graph out of scale

### ISSUE THREAD

**Issue by lkz0ne** [elC0mpa/OLED_SSD1306_Chart#10]
I am writting a class work using ssd1306 and this library. My classwork is a electronic load.

I need to plot 2 graph. One with the current being drained from source and another with the voltage of the source.

The graph of current is totally out of scale. I need to increase the current to 3~4 Amps to it show the first Amp on the graph.

Not is problem with wrong formulas or that stuff, because I've tested the formulas in other environment before.

Furthermore, the configuration of the library that i am using is the following:

```
  display.begin(SSD1306_SWITCHCAPVCC, 0x3c);
  display.clearDisplay();
  display.setChartCoordinates(0, 60);      //Chart lower left coordinates (X, Y)
  display.setChartWidthAndHeight(123, 60); //Chart width = 123 and height = 60
  display.setXIncrement(5);                //Distance between Y points will be 5px
  display.setYLimits(0, 14);              //Ymin = 0 and Ymax = 100 for first chart
  display.setYLimits(0, 3, 1);           //Ymin = 0 and Ymax = 100 for second chart
  display.setYLimitLabels("0", "14");
  display.setYLimitLabels("0", "3", 1);
  display.setAxisDivisionsInc(12, 6); //Each 12 px a division will be painted in X axis and each 6px in Y axis
  display.setYLabelsVisible(true);
  display.setPlotMode(DOUBLE_PLOT_MODE); //Set double plot mode
  display.setMidLineVisible(mid_line_visible);
  display.setLineThickness(LIGHT_LINE);
  display.setLineThickness(NORMAL_LINE, 1);
  display.drawChart(); //Update the buffer to draw the cartesian chart
  display.display();
```
and in the graph update part:

sometimes i need to do current_value*10 to see some motion in the graph:

```
  if (!display.updateChart( voltage_value, current_value*3 )) //Value between Ymin and Ymax will be added to chart
  {
    display.clearDisplay(); //If chart is full, it is drawn again
    mid_line_visible = !mid_line_visible;
    display.setMidLineVisible(mid_line_visible);
    display.drawChart();
  }
```

Moreover, the formula i am using for current_value is the standard formula for ICS758 hall effect sensor. That is the following:

```
  current_value = (5.0 / 1023.0) * analogRead(A0);

  current_value = current_value - 2.5 + 0.007;

  current_value = current_value / 0.04;

```

Why this? How to solve this out of scale graph?

Thanks in advanced.

**Comment by lkz0ne** [comment]
The problem is observable with the second graph rather than the first. The graph where I do set display.setYLimits(0, 3, 1);

**Comment by lkz0ne** [comment]
I figured out that the problem is around this function 

// Set Ymin and Ymax for each cartesian chart
display.setYLimits(double ylo, double yhi, uint8_t chart = 0);

I have two graph on my application.

The software is taking the scale of the first graph and using to scale the second too. 

That is, 
display.setYLimits(0, 3, 1); is not working.

Is this fixable?

Aren't this lib capable to draw two graph with different scales?

**Comment by elC0mpa** [comment]
Please do the following and let me know about the result
Open double plot mode example and modify lines 42 and 59 to change the limit of second chart to 50
Please execute this and tell me if it works as expected.
I ask you this because right now I haven't the environment updated to test this, I will be waiting for your answer

**Comment by lkz0ne** [comment]
I did the test.
As expected the second graph is with the same scale as the first.
First chart are with the scale of 0 to 100. The second chart that was changed to a scale of 0 to 50 are with a scale of 0 to 100 too.
Is this fixable?

**Comment by lkz0ne** [comment]
Maybe the error are in the line 264 of the library?

Updating to _y_max_value[1] and _y_min_value[1] (note the vector index 1)
264       double secondY = (secondValue - _y_min_values[1]) * (-semiHeight) / (_y_max_values[0] - _y_min_values[0]) + _y_lower_left_coordinate - semiHeight;

**Comment by elC0mpa** [comment]
Excellent observation!!!!
I will work on this but maybe you will need to wait until next weekend. Anyways I think it would be a great idea that you make a Pull Request with this fix if you agree of course

**Comment by lkz0ne** [comment]
Done. I hope it helps.
