### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hairyloon** [elC0mpa/OLED_SSD1306_Chart#2]
Hi,
just to let you know you're missing a "g" in line 29 It reads "Wire.bein();"

**Comment by elC0mpa** [comment]
Thank you, I just realized it right now, I will fix this typo and later I will commit the changes.

**Comment by elC0mpa** [comment]
@Hairyloon, the typos were already fixed. I will appreciate if you let me know if you are able to executes the examples now. Thanks again

**Comment by Hairyloon** [comment]
Sorry, I hadn't noticed that you'd fixed them.
Works fine now.

**Comment by elC0mpa** [comment]
Ok @Hairyloon, I just released a New version of the library with some changes in documentation.

**Comment by Hairyloon** [comment]
Sorry, I hadn't noticed that you'd fixed them.
Works fine now.
