### ISSUE TITLE
Multiple devices crash.

### ISSUE THREAD

**Issue by garymeg** [elC0mpa/OLED_SSD1306_Chart#6]
I have a setup to read Canbus data from a car. i want a graph of data with the lcd to display text about said graph, i have 1602 i2c lcd, 64x128 i2c oled and spi mcp2515 running on nano.
mcp and oled works fine
mcp and lcd works fine
oled and lcd works fine but
mcp oled and lcd nano freezes at drawdisplay. 
tested for freeze by using a serial.print("test point") and moving it down through code untill it stopped printing. code can be supplied if needed. 
tested oled, mcp and lcd with #ifdef to be able to switch each on and off in turn.

**Comment by elC0mpa** [comment]
Ok, I can't do too much with this information you are giving me. But I can think about two things
- First of all, use the same configuration and just use the Adafruit library to work with these displays
- If this still works, try to do the same with other MUC and let me know

The thing is that I don't think this problem will be related to the library
Let me know about this

**Comment by elC0mpa** [comment]
@garymeg any comments about this?
