### ISSUE TITLE
wrong scale on second chart after update chart

### ISSUE THREAD

**Issue by renedeboer** [elC0mpa/OLED_SSD1306_Chart#8]
after updatechart my second chart displays values near zero. Only the first run works great.
https://github.com/elC0mpa/OLED_SSD1306_Chart/blob/f4e6a79a7aadce682386f2f592e5e47d5ebf6580/src/OLED_SSD1306_Chart.cpp#L264
do _y_max_values and _y_min_values have to refer to index 1 ??

**Comment by lkz0ne** [comment]
good news?

**Comment by elC0mpa** [comment]
@renedeboer this is solved thanks to @lkz0ne. I will create a new release later, if you need it right now you can just clone master branch. Remember to give a ⭐  to the repo if you find it usefull
