### ISSUE TITLE
Is possible to insert values to the X axys?

### ISSUE THREAD

**Issue by lkz0ne** [elC0mpa/OLED_SSD1306_Chart#9]
I need to create a graph with specific X and Y values.
Is there a way to insert values to the X and Y values, rather only to the Y value in the graph?

**Comment by elC0mpa** [comment]
Later I will analize in a better way what you are asking, but maybe you coud achieve it by configuring label in Y axis

**Comment by lkz0ne** [comment]
Ok

**Comment by elC0mpa** [comment]
I thik the only way to do that right now is that distance between each X point will be the same. If this is your case, you might only tell the API to draw your Y points. Tell me if you already solved this to close this issue

**Comment by lkz0ne** [comment]
Not solved, but i will close.
